CREATE DATABASE IF NOT EXISTS BD_APP_MUSICA;
USE BD_APP_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF INTEGER(11) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO TIMESTAMP,
    BATIDA VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    QUANTIDADE_MUSICA INTEGER NOT NULL,
    FK_CPF_ARTISTA INTEGER,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);
CREATE TABLE IF NOT EXISTS FAIXA(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
LANCAMENTO_DATA DATE NOT NULL,
TEMPO_MUSICA TIMESTAMP,
FK_ID_ALBUM INTEGER,
FK_ID_GENERO INTEGER,
FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)

);