CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    TIPO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS PRODUTO(
CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    VALOR INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    VALIDADE DATE NOT NULL,
    FK_ID_CATEGORIA INT,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_CODIGO_PRODUTO INT,
    FK_CNPJ_FORNECEDOR VARCHAR(14),
    FOREIGN KEY (FK_CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);

